### PR TITLE
Braintree.

### PR DESCRIPTION
**Pull request by bvvnbsp**

### CODE REVIEW

**Comment by Guppymehra** [comment]
how we give the api name and display name in custom filed
 of braintree

**Comment by bvvnbsp** [comment]
Sorry I don't understand, can you explain more details?
You mean braintree point configuration, if yes, now we used mine sandbox account, first need deploy and test. Then we will setup your braintree point.

**Comment by Guppymehra** [comment]
there are some error in brain tree how i can solve

**Comment by bvvnbsp** [comment]
It's your local machine?
Check you ENV config in console if they exists.
BRAINTREE_ENV=sandbox
BRAINTREE_MERCHANT_ID=5wtkz2s4m7yjnjss
BRAINTREE_PUBLIC_KEY=rq4wnxsrqfrg6m8f
BRAINTREE_PRIVATE_KEY=a92624867a204b9526ea6d49b0a14d2e

1) "rails c"
2) ENV['BRAINTREE_PRIVATE_KEY']

you can use your own configs, it's mine braintree sandbox

**Comment by Guppymehra** [comment]
please i need braintree production account setting.

**Comment by Guppymehra** [comment]
My Error is Failed to create customer. Expiration date is required. Credit card number is required. Credit card must include number, payment_method_nonce, or venmo_sdk_payment_method_code.

**Pull request merged**
